version: '3'
services:
  database:
    image: "postgres:10.13"
    environment:
      - POSTGRES_DB=messenger
      - POSTGRES_USER=messenger
      - POSTGRES_PASSWORD=messenger
    ports:
      - "5432:5432"
  localstack:
    image: "localstack/localstack:0.10.9"
    environment:
      - SERVICES=sqs
    ports:
      - "4576:4576"
      - "8081:8080"
